import React from "react";

export default function Spinner() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
      width="80"
      height="80"
    >
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-1.375s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(30 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-1.25s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(60 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-1.125s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(90 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-1s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(120 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.875s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(150 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.75s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(180 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.625s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(210 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.5s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(240 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.375s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(270 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.25s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(300 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="-0.125s"
          repeatCount="indefinite"
        />
      </rect>
      <rect
        x="47"
        y="24"
        rx="9.4"
        ry="4.8"
        width="6"
        height="12"
        fill="#1d0e0b"
        transform="rotate(330 50 50)"
      >
        <animate
          attributeName="opacity"
          values="1;0"
          keyTimes="0;1"
          dur="1.5s"
          begin="0s"
          repeatCount="indefinite"
        />
      </rect>
    </svg>
  );
}
